### ISSUE TITLE
A Gui

### ISSUE THREAD

**Issue by Harshil783** [JRudransh/Clipboard_History#2]
Having Gui For This App Will Be Great!

**Comment by JRudransh** [comment]
Great...
Do you have any suggestions on what features are useful?

**Comment by JRudransh** [comment]
I will be happy to work on it

**Comment by Harshil783** [comment]
hey! Me And My Friend Want to work on project called PyClipSync And So I Decide Can we be a collaborator and help your project grow

**Comment by JRudransh** [comment]
I am working on some projects. Text me after 1 hour on telegram @JRudransh.
